export type PatternCategory =
  | "Actions"
  | "Feedback"
  | "Forms"
  | "Navigation"
  | "Selection"
  | "Data display"
  | "Layout"
  | "Calendar"
  | "Tasks";

export interface PatternEntry {
  number: number;
  slug: string;
  title: string;
  figmaName: string;
  figmaNodeId: string;
  category: PatternCategory;
  implementation: string;
  screenshot: string;
  dimensions: string[];
  variantSummary: string;
}

export const patternEntries: PatternEntry[] = [
  {
    number: 1,
    slug: "button",
    title: "Button",
    figmaName: "buttons-primary",
    figmaNodeId: "14051:28684",
    category: "Actions",
    implementation: "Button",
    screenshot: "01_Button.png",
    dimensions: ["28 px", "32 px", "40 px", "48 px"],
    variantSummary: "4 intents · 3 types · 4 sizes · 2 visual states",
  },
  {
    number: 2,
    slug: "callout",
    title: "Callout",
    figmaName: "C - Desktop - Callout",
    figmaNodeId: "18874:22",
    category: "Feedback",
    implementation: "Callout",
    screenshot: "02_Callout.png",
    dimensions: ["920 × 72 px"],
    variantSummary: "Line or icon · default, info, warning, error",
  },
  {
    number: 3,
    slug: "card-modal",
    title: "Cards, Slots and Modal",
    figmaName: "C - Desktop - Card / .slot - Modal",
    figmaNodeId: "18264:9755",
    category: "Layout",
    implementation: "Card · Modal",
    screenshot: "03_Cards_Slots_and_Modal.png",
    dimensions: ["Card 371 × 140 px", "Modal 571 × 487 px"],
    variantSummary: "Card surface · modal shell · optional header and actions",
  },
  {
    number: 4,
    slug: "calendar-drawer",
    title: "Calendar Drawer",
    figmaName: "C - Desktop - Calendar Drawer",
    figmaNodeId: "18332:4420",
    category: "Calendar",
    implementation: "CalendarDrawer",
    screenshot: "04_Calendar_Drawer.png",
    dimensions: ["320 × 840 px"],
    variantSummary: "Task, imported event and block entries",
  },
  {
    number: 5,
    slug: "checkbox",
    title: "Checkbox",
    figmaName: "C - Desktop - Checkbox",
    figmaNodeId: "18093:8161",
    category: "Selection",
    implementation: "Checkbox",
    screenshot: "05_Checkbox.png",
    dimensions: ["12 px", "16 px", "24 px"],
    variantSummary: "Checked, unchecked, priority and milestone",
  },
  {
    number: 6,
    slug: "radiobox",
    title: "Radiobox",
    figmaName: "C - Desktop - Radiobox",
    figmaNodeId: "18689:20",
    category: "Selection",
    implementation: "Radio",
    screenshot: "06_Radiobox.png",
    dimensions: ["12 px", "16 px", "24 px"],
    variantSummary: "Filled and unfilled · 3 sizes",
  },
  {
    number: 7,
    slug: "breadcrumb",
    title: "Breadcrumb",
    figmaName: "C - Desktop - Breadcrumb",
    figmaNodeId: "14050:25251",
    category: "Navigation",
    implementation: "Breadcrumb",
    screenshot: "07_Breadcrumb.png",
    dimensions: ["20 px row", "8 px gap"],
    variantSummary: "Text, link, collapsed and responsive",
  },
  {
    number: 8,
    slug: "switcher",
    title: "Switcher",
    figmaName: "C - Desktop - Switcher",
    figmaNodeId: "18264:4860",
    category: "Navigation",
    implementation: "Switcher",
    screenshot: "08_Switcher.png",
    dimensions: ["28 px", "32 px", "40 px", "48 px"],
    variantSummary: "Four control sizes · single active item",
  },
  {
    number: 9,
    slug: "form",
    title: "Form",
    figmaName: "C - Desktop - Input Field / Input Group",
    figmaNodeId: "18296:117",
    category: "Forms",
    implementation: "InputField · InputGroup",
    screenshot: "09_Form.png",
    dimensions: ["28 px", "32 px", "40 px", "48 px"],
    variantSummary: "Default, hover, filled, disabled · default and tinted",
  },
  {
    number: 10,
    slug: "date-picker",
    title: "Date Picker",
    figmaName: "C - Desktop - Date Picker",
    figmaNodeId: "18130:2289",
    category: "Forms",
    implementation: "DatePicker",
    screenshot: "10_Date_Picker.png",
    dimensions: ["280 × 281 px", "552 × 281 px range"],
    variantSummary: "Single date and date range",
  },
  {
    number: 11,
    slug: "dropdown",
    title: "Dropdown",
    figmaName: "C - Desktop - Dropdown Button / Meta Menu",
    figmaNodeId: "18264:3763",
    category: "Forms",
    implementation: "Dropdown · MetaMenu",
    screenshot: "11_Dropdown.png",
    dimensions: ["28 px", "32 px", "40 px", "48 px"],
    variantSummary: "Single, key-value, icon · menu variants",
  },
  {
    number: 12,
    slug: "filter-bar",
    title: "Filter Bar",
    figmaName: "C - Desktop - Filter Bar",
    figmaNodeId: "18264:5422",
    category: "Navigation",
    implementation: "FilterBar",
    screenshot: "12_Filter_Bar.png",
    dimensions: ["1154 × 32 px"],
    variantSummary: "Search · active filters · sorting",
  },
  {
    number: 13,
    slug: "sidebar",
    title: "Sidebar",
    figmaName: "C - Desktop - Sidebar Combined",
    figmaNodeId: "18554:9802",
    category: "Navigation",
    implementation: "Sidebar",
    screenshot: "13_Sidebar.png",
    dimensions: ["64 px primary rail", "328 × 840 px combined"],
    variantSummary: "Level 1, level 2, blocks and combined",
  },
  {
    number: 14,
    slug: "switch",
    title: "Switch",
    figmaName: "C - Desktop - Switch",
    figmaNodeId: "14051:29412",
    category: "Selection",
    implementation: "Switch",
    screenshot: "14_Switch.png",
    dimensions: ["24 px row"],
    variantSummary: "On and off · left and right alignment",
  },
  {
    number: 15,
    slug: "slider",
    title: "Slider",
    figmaName: "C - Desktop - Slider / Step Slider",
    figmaNodeId: "14054:38027",
    category: "Forms",
    implementation: "Slider",
    screenshot: "15_Slider.png",
    dimensions: ["400 × 8 px", "720 × 38 px stepped"],
    variantSummary: "Continuous and 10% increments",
  },
  {
    number: 16,
    slug: "tab-select",
    title: "Tab Select",
    figmaName: "C - Desktop - Tab Select Row",
    figmaNodeId: "18260:9452",
    category: "Selection",
    implementation: "TabSelect",
    screenshot: "16_Tab_Select.png",
    dimensions: ["28 px", "32 px", "40 px", "48 px"],
    variantSummary: "Default and music item rows · selected state",
  },
  {
    number: 17,
    slug: "tab-bar",
    title: "Tab Bar",
    figmaName: "C - Desktop - Tab Bar",
    figmaNodeId: "18654:15697",
    category: "Navigation",
    implementation: "TabBar",
    screenshot: "17_Tab_Bar.png",
    dimensions: ["28 px", "32 px", "40 px", "48 px"],
    variantSummary: "Continuous baseline · active indicator",
  },
  {
    number: 18,
    slug: "tags",
    title: "Tags",
    figmaName: "C - Desktop - tag Bar",
    figmaNodeId: "18462:12121",
    category: "Data display",
    implementation: "Tag",
    screenshot: "18_Tags.png",
    dimensions: ["28 px", "32 px", "40 px", "48 px"],
    variantSummary: "Category tones · optional icon and remove action",
  },
  {
    number: 19,
    slug: "toggle-group",
    title: "Toggle Group",
    figmaName: "C - Desktop - Toggle Bar",
    figmaNodeId: "18260:9030",
    category: "Selection",
    implementation: "ToggleGroup",
    screenshot: "19_Toggle_Group.png",
    dimensions: ["28 px", "32 px", "40 px", "48 px"],
    variantSummary: "Single active item · four sizes",
  },
  {
    number: 20,
    slug: "search-field",
    title: "Search Field",
    figmaName: "C - Desktop - Search Field",
    figmaNodeId: "18279:108",
    category: "Forms",
    implementation: "SearchField",
    screenshot: "20_Search_Field.png",
    dimensions: ["120 px rest", "320 px focused", "28/32/40/48 px high"],
    variantSummary: "Default, hover, focused, filled",
  },
  {
    number: 21,
    slug: "page-header",
    title: "Page Header",
    figmaName: "C - Desktop - Page Header",
    figmaNodeId: "19097:47874",
    category: "Layout",
    implementation: "PageHeader",
    screenshot: "21_Page_Header.png",
    dimensions: ["1170 × 56 px"],
    variantSummary: "Content and calendar headers",
  },
  {
    number: 22,
    slug: "ui-shell",
    title: "UI Shell",
    figmaName: "C - 1440 - UI Shell",
    figmaNodeId: "18096:2402",
    category: "Layout",
    implementation: "UiShell",
    screenshot: "22_UI_Shell.png",
    dimensions: ["1520 × 840 px"],
    variantSummary: "With sidebar and without sidebar",
  },
  {
    number: 23,
    slug: "calendar-item-task",
    title: "Calendar Item Task",
    figmaName: ".calendar item - task",
    figmaNodeId: "18093:8195",
    category: "Calendar",
    implementation: "CalendarItem kind=task",
    screenshot: "23_Calendar_Item_Task.png",
    dimensions: ["250 × 48 px"],
    variantSummary: "Default, selected, priority, dragged, placeholder",
  },
  {
    number: 24,
    slug: "calendar-item-imported",
    title: "Calendar Item Imported Calendar",
    figmaName: ".calendar item - importet calendar",
    figmaNodeId: "18093:8135",
    category: "Calendar",
    implementation: "CalendarItem kind=event",
    screenshot: "24_Calendar_Item_Imported_Calendar.png",
    dimensions: ["250 × 48 px"],
    variantSummary: "Default, urgent, selected, dragged, placeholder",
  },
  {
    number: 25,
    slug: "calendar-item-block",
    title: "Calendar Item Block",
    figmaName: ".calendar item - block",
    figmaNodeId: "18529:9448",
    category: "Calendar",
    implementation: "CalendarItem kind=block",
    screenshot: "25_Calendar_Item_Block.png",
    dimensions: ["250 × 48 px"],
    variantSummary: "Default, selected, dragged, placeholder",
  },
  {
    number: 26,
    slug: "task-add-item",
    title: "Task Add Item",
    figmaName: "C - Desktop - Add ItemItem",
    figmaNodeId: "18529:7288",
    category: "Tasks",
    implementation: "AddTask",
    screenshot: "26_Task_Add_Item.png",
    dimensions: ["640 × 48 px", "640 × 190 px active"],
    variantSummary: "Inactive, active and subtask",
  },
  {
    number: 27,
    slug: "task-group-header",
    title: "Task Group Header List Item",
    figmaName: "C - Desktop - Task Group Header List Item",
    figmaNodeId: "18529:7272",
    category: "Tasks",
    implementation: "TaskGroupHeader",
    screenshot: "27_Task_Group_Header_List_Item.png",
    dimensions: ["640 × 32 px"],
    variantSummary: "Default and hover",
  },
  {
    number: 28,
    slug: "milestone-group-header",
    title: "Milestone Group Header List Item",
    figmaName: "C - Desktop - Milestone Group Header List Item",
    figmaNodeId: "18595:20135",
    category: "Tasks",
    implementation: "TaskGroupHeader milestone",
    screenshot: "28_Milestone_Group_Header_List_Item.png",
    dimensions: ["640 × 32 px"],
    variantSummary: "Default and hover",
  },
  {
    number: 29,
    slug: "task-list-item",
    title: "Task List Item",
    figmaName: "C - Desktop - Task List Item",
    figmaNodeId: "18519:13887",
    category: "Tasks",
    implementation: "TaskListItem",
    screenshot: "29_Task_List_Item.png",
    dimensions: ["640 × 67–76 px"],
    variantSummary: "Default, hover, dragged, placeholder · favorite",
  },
  {
    number: 30,
    slug: "task-group",
    title: "Task Group",
    figmaName: "C - Desktop - Task Group",
    figmaNodeId: "18529:7756",
    category: "Tasks",
    implementation: "TaskGroup",
    screenshot: "30_Task_Group.png",
    dimensions: ["640 × 254 px"],
    variantSummary: "Default, dragged and placeholder",
  },
  {
    number: 31,
    slug: "milestone-list-item",
    title: "Milestone List Item",
    figmaName: "C - Desktop - Milestone List Item",
    figmaNodeId: "18595:20165",
    category: "Tasks",
    implementation: "TaskListItem milestone",
    screenshot: "31_Milestone_List_Item.png",
    dimensions: ["640 × 63–77 px"],
    variantSummary: "Default, hover, dragged, placeholder · favorite",
  },
  {
    number: 32,
    slug: "milestone-task-group",
    title: "Milestone Group Task Group",
    figmaName: "C - Desktop - Milestone GroupTask Group",
    figmaNodeId: "18595:20499",
    category: "Tasks",
    implementation: "TaskGroup milestone",
    screenshot: "32_Milestone_GroupTask_Group.png",
    dimensions: ["640 × 522 px"],
    variantSummary: "Milestone progression group",
  },
  {
    number: 33,
    slug: "task-modal-header",
    title: "Aufgaben Modal Header",
    figmaName: "C - Aufgaben - Modal - Header",
    figmaNodeId: "18553:10832",
    category: "Tasks",
    implementation: "TaskModalHeader",
    screenshot: "33_Aufgaben_Modal_Header.png",
    dimensions: ["528 × 76–128 px"],
    variantSummary: "Unfocused, focused and filled-out",
  },
  {
    number: 34,
    slug: "task-modal-menu",
    title: "Aufgaben Modal Menu Rechts",
    figmaName: "C - Aufgaben - Modal - Menu rechts",
    figmaNodeId: "18553:12713",
    category: "Tasks",
    implementation: "TaskModalMenu",
    screenshot: "34_Aufgaben_Modal_Menu_Rechts.png",
    dimensions: ["232 × 160 px"],
    variantSummary: "Expandable task properties",
  },
  {
    number: 35,
    slug: "task-modal-slot",
    title: "Aufgaben Modal Task Slot",
    figmaName: ".slot - aufgaben modal - task",
    figmaNodeId: "18546:10330",
    category: "Tasks",
    implementation: "TaskModalSlot",
    screenshot: "35_Aufgaben_Modal_Task_Slot.png",
    dimensions: ["848 × 566 px"],
    variantSummary: "Header, body, property menu and footer",
  },
];

export const patternCategories: PatternCategory[] = [
  "Actions",
  "Forms",
  "Selection",
  "Navigation",
  "Feedback",
  "Data display",
  "Calendar",
  "Tasks",
  "Layout",
];

export function getPatternEntry(slug: string) {
  return patternEntries.find((entry) => entry.slug === slug);
}
